import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowRight, ArrowUpRight, BookOpen, CalendarDays, GraduationCap, MapPin, Users, ClipboardList, ShieldCheck, LibraryBig, Images } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { SectionHeading } from '@/components/site-layout';
import { FallbackImg } from '@/components/fallback-img';
import { Reveal, CountUp } from '@/components/portal-motion';
import heroFallback from '@/assets/hero-fallback.jpg';
import { docHref } from '@/lib/official-nav';
import { college, courseGroups, images, notices, programmes, siteUrl } from '@/lib/college';
import { seo } from '@/lib/seo';

export const Route = createFileRoute('/')({ staticData: { sitemap: true },
  head: () => ({ ...seo({ title: 'K.L.P. College, Rewari | Kishan Lal Public College', description: 'Discover Kishan Lal Public College in Rewari: programmes, admissions, campus life, notices and student services.', path: '/' }), scripts: [{ type: 'application/ld+json', children: JSON.stringify({ '@context': 'https://schema.org', '@type': 'CollegeOrUniversity', name: college.name, alternateName: college.shortName, url: siteUrl, foundingDate: '1964', telephone: college.phone, email: college.email, address: { '@type': 'PostalAddress', streetAddress: 'Delhi Road, Near Abhay Singh Chowk', addressLocality: 'Rewari', addressRegion: 'Haryana', postalCode: '123401', addressCountry: 'IN' } }) }] }),
  component: Home,
});

const access = [
  { title: 'Students', text: 'Results, notices and time tables', icon: GraduationCap, links: [{ label: 'Results', to: '/academics/results' }, { label: 'Notices', to: '/notices' }, { label: 'Time table', to: '/academics/time-table' }] },
  { title: 'Teachers', text: 'Departments, resources and committees', icon: LibraryBig, links: [{ label: 'Faculty resources', to: '/faculty/faculty-e-resources' }, { label: 'Departments', to: '/faculty/departments' }, { label: 'Committees', to: '/faculty/committees-cells' }] },
  { title: 'Administration', text: 'Staff access and college information', icon: ShieldCheck, links: [{ label: 'Staff login', href: college.staffPortal }, { label: 'Tenders', to: '/more/tenders' }, { label: 'Contact', to: '/contact' }] },
];

function Home() { return <>
  <section className="home-hero"><FallbackImg className="hero-image" src={images.building} fallback={heroFallback} alt="K.L.P. College campus building in Rewari" fetchPriority="high"/><div className="hero-shade"/><div className="site-container hero-content"><div className="hero-copy"><p className="eyebrow light-eyebrow"><span className="eyebrow-line"/> Rewari, Haryana · Established 1964</p><h1>Kishan Lal<br/>Public College</h1><p className="hero-lead">A place to learn, grow and find your direction. Rooted in Rewari, reaching beyond.</p><div className="hero-buttons"><Button asChild size="lg"><a href={college.apply} target="_blank" rel="noopener noreferrer">Apply Now <ArrowUpRight size={17}/></a></Button><Button asChild variant="outline" size="lg" className="hero-outline"><Link to="/academics">Explore Courses <ArrowRight size={17}/></Link></Button></div></div><div className="hero-side-note"><span>Established 1964</span><span>Learning with purpose<br/>in Rewari</span></div></div></section>
  <div className="notice-ticker"><div className="site-container ticker-inner"><Link to="/notices" className="ticker-label">Latest notices <ArrowUpRight size={15}/></Link><div className="ticker-window"><div className="ticker-track">{[...notices, ...notices].map((notice, i) => <a key={`${notice.title}-${i}`} href={docHref(notice.href, notice.title)} tabIndex={i >= notices.length ? -1 : undefined}><span>{notice.date}</span> {notice.title} <ArrowUpRight size={13}/></a>)}</div></div></div></div>
  <section className="quick-section"><div className="site-container quick-grid"><Link to="/admissions"><GraduationCap size={24}/><span><strong>Admissions</strong><small>Begin your journey</small></span><ArrowUpRight size={18}/></Link><Link to="/academics"><BookOpen size={24}/><span><strong>Programmes</strong><small>Find your path</small></span><ArrowUpRight size={18}/></Link><Link to="/notices"><CalendarDays size={24}/><span><strong>Latest notices</strong><small>Stay up to date</small></span><ArrowUpRight size={18}/></Link><Link to="/contact"><MapPin size={24}/><span><strong>Visit us</strong><small>Rewari, Haryana</small></span><ArrowUpRight size={18}/></Link></div></section>
  <section className="section access-section"><div className="site-container"><Reveal><SectionHeading eyebrow="Quick access" title="Your next step, within reach."/></Reveal><div className="access-grid">{access.map(({ title, text, icon: Icon, links }) => <Reveal key={title}><article className="access-card"><div className="access-icon"><Icon size={26}/></div><h3>{title}</h3><p>{text}</p><div className="access-links">{links.map(link => 'href' in link ? <a key={link.label} href={link.href} target="_blank" rel="noopener noreferrer">{link.label}<ArrowUpRight size={14}/></a> : <Link key={link.label} to={link.to}>{link.label}<ArrowUpRight size={14}/></Link>)}</div></article></Reveal>)}</div></div></section>
  <section className="section section-intro"><div className="site-container intro-grid"><Reveal><SectionHeading eyebrow="A legacy of learning" title="Where tradition meets possibility."/><p className="body-copy">Established in 1964, Kishan Lal Public College is a co-educational institution in Rewari, affiliated with Indira Gandhi University, Meerpur. Across disciplines and experiences, the college creates space for students to discover what comes next.</p><Link className="text-link" to="/about">Get to know K.L.P. <ArrowUpRight size={18}/></Link></Reveal><Reveal><div className="intro-visual"><img src={images.grounds} alt="Students on the grounds of K.L.P. College" loading="lazy"/><span className="image-caption">A community built around learning.</span></div></Reveal></div><div className="site-container fact-strip"><div><strong><CountUp value={1964}/></strong><span>Established</span></div><div><strong><CountUp value={programmes.length}/></strong><span>Listed degree programmes</span></div><div><strong><CountUp value={3}/></strong><span>Fields of study</span></div></div></section>
  <section className="section section-programmes"><div className="site-container"><div className="section-top"><SectionHeading eyebrow="Academics" title="Find your field of study." description="Explore undergraduate and postgraduate pathways across the arts, commerce and sciences."/><Link className="text-link" to="/academics">View all programmes <ArrowUpRight size={18}/></Link></div><div className="programme-grid">{courseGroups.map(group => <Reveal key={group.title}><Link to="/academics" className="programme-card"><span className="programme-number">{group.icon} / FIELD OF STUDY</span><div><h3>{group.title}</h3><p>{group.label}</p><small className="programme-reveal">{group.courses.join(' · ')}</small></div><ArrowUpRight className="programme-arrow" size={23}/></Link></Reveal>)}</div></div></section>
  <section className="section section-notices"><div className="site-container notices-grid"><div><SectionHeading eyebrow="The latest" title="Stay in the know." description="Important announcements and updates from the college."/><Button asChild variant="outline" size="lg"><Link to="/notices">All notices <ArrowUpRight size={17}/></Link></Button></div><div className="notice-list">{notices.map((notice, index) => <a key={notice.title} href={docHref(notice.href, notice.title)} className="notice-row"><span className="notice-index">0{index + 1}</span><span className="notice-main"><small>{notice.category} · {notice.date}</small><strong>{notice.title}</strong></span><ArrowUpRight size={19}/></a>)}</div></div></section>
  <section className="campus-feature"><img src={images.hall} alt="K.L.P. College campus facilities" loading="lazy"/><div className="campus-feature-shade"/><div className="site-container campus-feature-content"><p className="eyebrow light-eyebrow">Beyond the classroom</p><h2>More to college<br/>than coursework.</h2><p>Explore the spaces, activities and communities that make K.L.P. College your own.</p><Button asChild size="lg"><Link to="/campus">Explore campus life <ArrowUpRight size={17}/></Link></Button></div></section>
  <section className="section home-more"><div className="site-container home-more-grid"><Link to="/faculty"><Users size={28}/><h2>Our academic community</h2><p>Explore departments, teaching staff and committees.</p><span>Meet the faculty <ArrowUpRight size={16}/></span></Link><Link to="/gallery"><Images size={28}/><h2>Moments on campus</h2><p>Browse photos from college events and everyday life.</p><span>Visit gallery <ArrowUpRight size={16}/></span></Link><Link to="/activities"><ClipboardList size={28}/><h2>Life beyond class</h2><p>Discover clubs, service initiatives and student activities.</p><span>Explore activities <ArrowUpRight size={16}/></span></Link></div></section>
  <section className="section final-cta"><div className="site-container final-cta-inner"><div><p className="eyebrow">Your next step</p><h2>Ready to begin?</h2><p>Find the information you need to start your journey at K.L.P. College.</p></div><Button asChild size="lg"><Link to="/admissions">Admissions information <ArrowUpRight size={17}/></Link></Button></div></section>
</>; }
