/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AboutDirectoryRouteImport } from './routes/about-directory'
import { Route as AcademicResourcesRouteImport } from './routes/academic-resources'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AlumniRouteImport } from './routes/alumni'
import { Route as AskRouteImport } from './routes/ask'
import { Route as CampusRouteImport } from './routes/campus'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as IqacRouteImport } from './routes/iqac'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SectionPageRouteImport } from './routes/$section.$page'
import { Route as ApiAskRouteImport } from './routes/api/ask'
import { Route as ProgrammesSlugRouteImport } from './routes/programmes.$slug'
import { Route as ApiPublicDocRouteImport } from './routes/api/public/doc'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutDirectoryRoute = AboutDirectoryRouteImport.update({
  id: '/about-directory',
  path: '/about-directory',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicResourcesRoute = AcademicResourcesRouteImport.update({
  id: '/academic-resources',
  path: '/academic-resources',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniRoute = AlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusRoute = CampusRouteImport.update({
  id: '/campus',
  path: '/campus',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IqacRoute = IqacRouteImport.update({
  id: '/iqac',
  path: '/iqac',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionPageRoute = SectionPageRouteImport.update({
  id: '/$section/$page',
  path: '/$section/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesSlugRoute = ProgrammesSlugRouteImport.update({
  id: '/programmes/$slug',
  path: '/programmes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDocRoute = ApiPublicDocRouteImport.update({
  id: '/api/public/doc',
  path: '/api/public/doc',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-directory': typeof AboutDirectoryRoute
  '/academic-resources': typeof AcademicResourcesRoute
  '/academics': typeof AcademicsRoute
  '/activities': typeof ActivitiesRoute
  '/admissions': typeof AdmissionsRoute
  '/alumni': typeof AlumniRoute
  '/ask': typeof AskRoute
  '/campus': typeof CampusRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/iqac': typeof IqacRoute
  '/notices': typeof NoticesRoute
  '/students': typeof StudentsRoute
  '/$section/$page': typeof SectionPageRoute
  '/api/ask': typeof ApiAskRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/api/public/doc': typeof ApiPublicDocRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-directory': typeof AboutDirectoryRoute
  '/academic-resources': typeof AcademicResourcesRoute
  '/academics': typeof AcademicsRoute
  '/activities': typeof ActivitiesRoute
  '/admissions': typeof AdmissionsRoute
  '/alumni': typeof AlumniRoute
  '/ask': typeof AskRoute
  '/campus': typeof CampusRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/iqac': typeof IqacRoute
  '/notices': typeof NoticesRoute
  '/students': typeof StudentsRoute
  '/$section/$page': typeof SectionPageRoute
  '/api/ask': typeof ApiAskRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/api/public/doc': typeof ApiPublicDocRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-directory': typeof AboutDirectoryRoute
  '/academic-resources': typeof AcademicResourcesRoute
  '/academics': typeof AcademicsRoute
  '/activities': typeof ActivitiesRoute
  '/admissions': typeof AdmissionsRoute
  '/alumni': typeof AlumniRoute
  '/ask': typeof AskRoute
  '/campus': typeof CampusRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/iqac': typeof IqacRoute
  '/notices': typeof NoticesRoute
  '/students': typeof StudentsRoute
  '/$section/$page': typeof SectionPageRoute
  '/api/ask': typeof ApiAskRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/api/public/doc': typeof ApiPublicDocRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-directory'
    | '/academic-resources'
    | '/academics'
    | '/activities'
    | '/admissions'
    | '/alumni'
    | '/ask'
    | '/campus'
    | '/compare'
    | '/contact'
    | '/documents'
    | '/faculty'
    | '/gallery'
    | '/iqac'
    | '/notices'
    | '/students'
    | '/$section/$page'
    | '/api/ask'
    | '/programmes/$slug'
    | '/api/public/doc'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-directory'
    | '/academic-resources'
    | '/academics'
    | '/activities'
    | '/admissions'
    | '/alumni'
    | '/ask'
    | '/campus'
    | '/compare'
    | '/contact'
    | '/documents'
    | '/faculty'
    | '/gallery'
    | '/iqac'
    | '/notices'
    | '/students'
    | '/$section/$page'
    | '/api/ask'
    | '/programmes/$slug'
    | '/api/public/doc'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-directory'
    | '/academic-resources'
    | '/academics'
    | '/activities'
    | '/admissions'
    | '/alumni'
    | '/ask'
    | '/campus'
    | '/compare'
    | '/contact'
    | '/documents'
    | '/faculty'
    | '/gallery'
    | '/iqac'
    | '/notices'
    | '/students'
    | '/$section/$page'
    | '/api/ask'
    | '/programmes/$slug'
    | '/api/public/doc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutDirectoryRoute: typeof AboutDirectoryRoute
  AcademicResourcesRoute: typeof AcademicResourcesRoute
  AcademicsRoute: typeof AcademicsRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AlumniRoute: typeof AlumniRoute
  AskRoute: typeof AskRoute
  CampusRoute: typeof CampusRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  DocumentsRoute: typeof DocumentsRoute
  FacultyRoute: typeof FacultyRoute
  GalleryRoute: typeof GalleryRoute
  IqacRoute: typeof IqacRoute
  NoticesRoute: typeof NoticesRoute
  StudentsRoute: typeof StudentsRoute
  SectionPageRoute: typeof SectionPageRoute
  ApiAskRoute: typeof ApiAskRoute
  ProgrammesSlugRoute: typeof ProgrammesSlugRoute
  ApiPublicDocRoute: typeof ApiPublicDocRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-directory': {
      id: '/about-directory'
      path: '/about-directory'
      fullPath: '/about-directory'
      preLoaderRoute: typeof AboutDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-resources': {
      id: '/academic-resources'
      path: '/academic-resources'
      fullPath: '/academic-resources'
      preLoaderRoute: typeof AcademicResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni': {
      id: '/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus': {
      id: '/campus'
      path: '/campus'
      fullPath: '/campus'
      preLoaderRoute: typeof CampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iqac': {
      id: '/iqac'
      path: '/iqac'
      fullPath: '/iqac'
      preLoaderRoute: typeof IqacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section/$page': {
      id: '/$section/$page'
      path: '/$section/$page'
      fullPath: '/$section/$page'
      preLoaderRoute: typeof SectionPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/$slug': {
      id: '/programmes/$slug'
      path: '/programmes/$slug'
      fullPath: '/programmes/$slug'
      preLoaderRoute: typeof ProgrammesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/doc': {
      id: '/api/public/doc'
      path: '/api/public/doc'
      fullPath: '/api/public/doc'
      preLoaderRoute: typeof ApiPublicDocRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutDirectoryRoute: AboutDirectoryRoute,
  AcademicResourcesRoute: AcademicResourcesRoute,
  AcademicsRoute: AcademicsRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdmissionsRoute: AdmissionsRoute,
  AlumniRoute: AlumniRoute,
  AskRoute: AskRoute,
  CampusRoute: CampusRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  DocumentsRoute: DocumentsRoute,
  FacultyRoute: FacultyRoute,
  GalleryRoute: GalleryRoute,
  IqacRoute: IqacRoute,
  NoticesRoute: NoticesRoute,
  StudentsRoute: StudentsRoute,
  SectionPageRoute: SectionPageRoute,
  ApiAskRoute: ApiAskRoute,
  ProgrammesSlugRoute: ProgrammesSlugRoute,
  ApiPublicDocRoute: ApiPublicDocRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
